theme = "tokyonight_transparent"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
bufferline = "multiple"
editor-config = true
rulers = [80, 120]

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
C-g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all"
]

[keys.normal.space]
e = [
      ":sh rm -f /tmp/unique-file-h21a434",
      ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
      ":insert-output echo \"x1b[?1049h\" > /dev/tty",
      ":open %sh{cat /tmp/unique-file-h21a434}",
      ":redraw"
]
