theme = "tokyonight_transparent"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
bufferline = "multiple"
editor-config = true
rulers = [80, 120]

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
