theme = "bogster"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
bufferline = "multiple"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

