require('config.theme')
require('config.nvim-tree')
require('config.alpha')
require('config.bufferline')
require('config.gitsigns')
require('config.fterm')
require('config.treesitter')
require('config.mason')
require('config.lsp')
require('config.telescope')
require('config.trouble')
require('config.lightbulb')
require('config.lualine')
require('config.autopairs')
require('config.cmp')
require('config.which-key')

